#!/usr/bin/env python3
"""Replay the M10 harness over the real Mooncake trace and write its artifacts.

The trace is real and its sha256 is recorded, but every number below comes from
the local simulator: no engine, GPU, or network was involved. The run is
therefore labelled SYNTHETIC_REPLAY / SYNTHETIC_UNCALIBRATED in NORMALIZED_WORK,
and :func:`_assert_no_stronger_claim` inspects every artifact's bytes *before*
they are written, so a run that would have claimed otherwise produces no file at
all rather than a file that has to be retracted.

Two things are written that a reader might not expect:

``fault_injection.csv``
    The modeled ledger is empty, because all three sources are derived from one
    decision log. An empty ledger is only evidence if the reconciler can be shown
    to produce a non-empty one, so a synthetic bundle with *known* faults is
    reconciled here too and both the expected and recovered ledgers are written.
``reconciliation.csv``
    Per-cell join health, so the empty ledger is visible per arm rather than
    only in aggregate.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import os
import shutil
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from prefill_cache_sim.calibration import (
    CalibrationStatus,
    EvidenceTier,
    MachineProvenance,
    TimeUnit,
)
from prefill_cache_sim.config import git_provenance
from prefill_cache_sim.replay import (
    DEFAULT_SHADOW_GATE,
    ENFORCEMENT_ENABLED,
    FROZEN_RANKING_STATISTIC,
    SCORE_METRICS,
    AttemptKey,
    FaultPlan,
    FieldPerturbation,
    LedgerEntry,
    RankingComparison,
    ReplayOutcome,
    ReplayPlan,
    ShadowDecision,
    SourceName,
    apply_faults,
    reconcile,
    run_replay,
    source_manifest,
    synthetic_bundle,
)
from prefill_cache_sim.trace import load_trace, to_simulation_requests

BLOCK_SIZE_TOKENS = 512
EVIDENCE_TIER = EvidenceTier.SYNTHETIC_REPLAY
CALIBRATION_STATUS = CalibrationStatus.SYNTHETIC_UNCALIBRATED
TIME_UNIT = TimeUnit.NORMALIZED_WORK

#: Size of the fault-injection fixture. Large enough to hold several retries.
FAULT_ATTEMPTS = 64
FAULT_SEED = 20261010

#: Digest index over every other artifact, written last so a torn set is
#: detectable rather than silently mixing two runs.
MANIFEST_NAME = "MANIFEST.json"
MANIFEST_SCHEMA_VERSION = "m10-artifact-manifest-v1"

#: Labels this run has not earned. Every artifact's bytes are checked before
#: any of them reach the output directory.
FORBIDDEN_LABELS = (
    TimeUnit.MILLISECONDS.value,
    CalibrationStatus.HW_CALIBRATED.value,
    EvidenceTier.HW_VALIDATED.value,
)

#: Inherited simulator field names carry an ``_ms`` suffix. They are normalized
#: work units, not wall-clock milliseconds; see PROVENANCE.md.
UNIT_NOTE = "FIELDS_SUFFIXED_MS_ARE_NORMALIZED_WORK_NOT_WALL_CLOCK"

LEDGER_FIELDS = (
    "scope",
    "kind",
    "logical_request_id",
    "attempt_index",
    "field_name",
    "sources",
    "values",
)


def _json_bytes(payload: object) -> bytes:
    # allow_nan=False: bare NaN/Infinity literals are not valid JSON, so a
    # poisoned score must fail loudly here instead of shipping an unparseable
    # file that a reader would have to guess at.
    return (
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    ).encode("utf-8")


def _csv_bytes(
    rows: Sequence[Mapping[str, object]], fieldnames: Sequence[str]
) -> bytes:
    # newline="" keeps csv's own \r\n terminators intact, exactly as writing
    # through an opened file handle would, so the bytes are the artifact.
    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(buffer, fieldnames=list(fieldnames))
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


def _manifest_bytes(artifacts: Mapping[str, bytes]) -> bytes:
    return _json_bytes(
        {
            "schema_version": MANIFEST_SCHEMA_VERSION,
            "algorithm": "sha256",
            "note": (
                "Digests of the artifacts generated by this run. This file is "
                "replaced last, so a reader that observes a digest mismatch is "
                "looking at a partially replaced set, not at one run's output."
            ),
            "files": {
                name: hashlib.sha256(payload).hexdigest()
                for name, payload in sorted(artifacts.items())
            },
        }
    )


def _assert_no_stronger_claim(name: str, payload: bytes) -> None:
    """Refuse to ship an artifact that names a label this run cannot support.

    The check runs on the bytes before they reach the output directory, so a
    run that would have overclaimed leaves the previous artifacts untouched
    instead of publishing a file that then has to be retracted.
    """
    text = payload.decode("utf-8")
    for label in FORBIDDEN_LABELS:
        if label in text:
            raise RuntimeError(f"{name} claims {label}; nothing here earned it")


def _write_artifacts(output_dir: Path, artifacts: Mapping[str, bytes]) -> None:
    """Stage every artifact in a temp directory, then move them into place.

    Replacing the whole directory in one rename would be atomic, but it would
    also delete files this script does not generate -- ``PROVENANCE.md`` is
    hand-written and lives here -- so each file is replaced individually with
    :func:`os.replace`. The staging directory is a sibling of the output
    directory to keep those renames on one filesystem, where they are atomic.

    Honest limitation: per-file renames leave a window in which a concurrent
    reader could see files from two runs. ``MANIFEST.json`` is written last and
    carries the digest of every other artifact, so such a reader can detect the
    mix instead of silently trusting it.
    """
    if MANIFEST_NAME not in artifacts:
        raise RuntimeError(f"artifact set must include {MANIFEST_NAME}")
    ordered = [name for name in sorted(artifacts) if name != MANIFEST_NAME]
    ordered.append(MANIFEST_NAME)

    output_dir.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(dir=output_dir.parent, prefix=".m10-staging-"))
    try:
        for name in ordered:
            (staging / name).write_bytes(artifacts[name])
        for name in ordered:
            os.replace(staging / name, output_dir / name)
    finally:
        # Only the staging directory is ever removed; the output directory and
        # anything in it that this script did not generate are left untouched.
        shutil.rmtree(staging, ignore_errors=True)


def _ledger_row(scope: str, entry: LedgerEntry) -> dict[str, Any]:
    return {
        "scope": scope,
        "kind": entry.kind.value,
        "logical_request_id": entry.logical_request_id,
        "attempt_index": entry.attempt_index,
        "field_name": entry.field_name,
        "sources": "|".join(source.value for source in entry.sources),
        "values": "|".join(entry.values),
    }


def _fault_plan(keys: dict[str, AttemptKey]) -> FaultPlan:
    """Damage three different attempts in three different ways.

    Separate keys are used per fault so that the published ledger exhibits each
    defect kind in isolation; the precedence between kinds is exercised by the
    test suite rather than by this artifact. The perturbed attempt is a retry,
    so recovering it also proves the join key survives a repeated logical
    request id.
    """
    return FaultPlan(
        drop=((SourceName.ENGINE_HIT, keys["dropped"]),),
        duplicate=((SourceName.CLIENT_LATENCY, keys["duplicated"]),),
        perturb=(
            FieldPerturbation(
                SourceName.ATTEMPT_TRACE, keys["perturbed"], "node_id", "node-injected"
            ),
        ),
    )


def _fault_injection_rows() -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Reconcile a bundle whose defects are known in advance.

    The expected ledger is derived by :func:`apply_faults` from the plan and the
    *clean* records, never by calling :func:`reconcile` and never by reading the
    damaged bundle back, so agreement between the two is a check on the
    reconciler rather than a restatement of it.
    """
    clean = synthetic_bundle(attempt_count=FAULT_ATTEMPTS, seed=FAULT_SEED)
    retries = [
        record.key for record in clean.engine_hits if record.key.attempt_index > 0
    ]
    keys = {
        "dropped": clean.engine_hits[3].key,
        "duplicated": clean.engine_hits[5].key,
        "perturbed": retries[0],
    }
    injection = apply_faults(clean, _fault_plan(keys))
    recovered = reconcile(injection.bundle)
    if recovered.ledger != injection.expected_ledger:
        raise AssertionError("reconciler did not recover the injected ledger exactly")

    rows = [_ledger_row("EXPECTED", entry) for entry in injection.expected_ledger]
    rows += [_ledger_row("RECOVERED", entry) for entry in recovered.ledger]
    summary = {
        "attempt_count": recovered.attempt_count,
        "expected_entries": len(injection.expected_ledger),
        "recovered_entries": len(recovered.ledger),
        "exact_match": True,
        "seed": FAULT_SEED,
        "targets": {name: key.to_dict() for name, key in keys.items()},
    }
    return rows, summary


def _assert_round_trips(
    outcome: ReplayOutcome,
    rankings: Mapping[str, RankingComparison | None],
    shadow: Mapping[str, tuple[ShadowDecision, ...]],
) -> None:
    """Check that every published record survives its own serialization.

    :class:`ReplayOutcome` itself is deliberately not round-tripped: its
    ``to_dict`` drops the source bundles and the per-attempt reconciled rows on
    purpose, so it has no ``from_dict`` and a round-trip would be meaningless.
    The records that *are* the evidence -- decisions, ranking comparisons, and
    ledger entries -- do have one, and each is rebuilt from its own payload
    here. A field that serializes to a type the reader rejects then fails now,
    while nothing has been written, instead of in whoever loads the artifact.

    Shadow decisions are additionally checked against the gate this run claims
    to publish, because a stated policy is only evidence if someone compares it
    to the expected one.
    """
    for metric, decisions in shadow.items():
        for decision in decisions:
            if decision.enforced:
                raise RuntimeError(
                    f"{metric}: shadow decision for {decision.candidate_arm_id} "
                    "reports itself enforced"
                )
            # A decision now states the thresholds it was judged against, which
            # only helps a reader if the published run states the *expected*
            # ones. Otherwise a permissive gate would simply be declared in the
            # artifact and go on looking self-consistent.
            if decision.policy != DEFAULT_SHADOW_GATE:
                raise RuntimeError(
                    f"{metric}: shadow decision for {decision.candidate_arm_id} "
                    f"was judged against {decision.policy.to_dict()}, not the "
                    f"default gate {DEFAULT_SHADOW_GATE.to_dict()}"
                )
            if ShadowDecision.from_dict(decision.to_dict()) != decision:
                raise RuntimeError(f"{metric}: shadow decision failed to round-trip")

    for metric, comparison in rankings.items():
        if comparison is None:
            continue
        if RankingComparison.from_dict(comparison.to_dict()) != comparison:
            raise RuntimeError(f"{metric}: ranking comparison failed to round-trip")

    for cell in outcome.cells:
        for entry in cell.reconciliation.ledger:
            if LedgerEntry.from_dict(entry.to_dict()) != entry:
                raise RuntimeError(f"{cell.arm_id}: ledger entry failed to round-trip")


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    loaded = load_trace(
        root / "mooncake_trace.jsonl", block_size_tokens=BLOCK_SIZE_TOKENS
    )
    requests = to_simulation_requests(loaded)
    provenance = git_provenance(root)

    plan = ReplayPlan()
    outcome = run_replay(
        plan,
        requests,
        trace_sha256=loaded.sha256,
        git_sha=provenance.sha,
        git_dirty=provenance.dirty,
        evidence_tier=EVIDENCE_TIER,
        machine=MachineProvenance.unknown(),
    )

    # Fail before writing anything: a published artifact that claims hardware it
    # never touched is worse than no artifact. `assert` would be stripped by -O.
    if outcome.machine != MachineProvenance.unknown():
        raise RuntimeError(
            "this script drives the local simulator and must not report machine "
            f"provenance, got {outcome.machine.to_dict()}"
        )
    if outcome.calibration_status is not CALIBRATION_STATUS:
        raise RuntimeError("synthetic replay must stay SYNTHETIC_UNCALIBRATED")
    if outcome.time_unit is not TIME_UNIT:
        raise RuntimeError("synthetic replay must stay in NORMALIZED_WORK")
    if outcome.evidence_tier is not EVIDENCE_TIER:
        raise RuntimeError("synthetic replay must stay SYNTHETIC_REPLAY")
    if ENFORCEMENT_ENABLED:
        raise RuntimeError("M10 records shadow decisions and must never enforce them")

    output_dir = root / "results/m10-synthetic"

    fault_rows, fault_summary = _fault_injection_rows()
    rankings = {metric: outcome.ranking_comparison(metric) for metric in SCORE_METRICS}
    shadow = {metric: outcome.shadow_decisions(metric) for metric in SCORE_METRICS}
    _assert_round_trips(outcome, rankings, shadow)

    payload = {
        "outcome": outcome.to_dict(),
        "ranking": {
            "frozen_statistic": FROZEN_RANKING_STATISTIC,
            "comparisons": {
                metric: None if item is None else item.to_dict()
                for metric, item in rankings.items()
            },
        },
        "shadow": {
            "enforced": False,
            "decisions": {
                metric: [decision.to_dict() for decision in decisions]
                for metric, decisions in shadow.items()
            },
        },
        "fault_injection": fault_summary,
        "provenance": {
            "trace_sha256": loaded.sha256,
            "trace_requests": len(requests),
            "block_size_tokens": BLOCK_SIZE_TOKENS,
            "git_sha": provenance.sha,
            "git_dirty": provenance.dirty,
            "evidence_tier": EVIDENCE_TIER.value,
            "calibration_status": CALIBRATION_STATUS.value,
            "time_unit": TIME_UNIT.value,
            "unit_note": UNIT_NOTE,
            "machine": MachineProvenance.unknown().to_dict(),
            "hardware_validation": "BLOCKED_NO_ENGINE_ACCESS",
            # The generator and the replay package are untracked at this commit,
            # so git_sha alone does not identify the code that produced these
            # numbers. These digests do; see the embedded note.
            "source_fingerprints": source_manifest(root),
        },
    }

    labels = {
        "evidence_tier": EVIDENCE_TIER.value,
        "calibration_status": CALIBRATION_STATUS.value,
        "time_unit": TIME_UNIT.value,
        "unit_note": UNIT_NOTE,
    }
    result_rows = [
        {
            "arm_id": cell.arm_id,
            "arm_role": cell.arm_role.value,
            "arrival_scale": cell.arrival_scale,
            "case_fingerprint": cell.case_fingerprint,
            **cell.result.to_dict(),
            **labels,
        }
        for cell in outcome.cells
    ]
    reconciliation_rows = [
        {
            "arm_id": cell.arm_id,
            "arrival_scale": cell.arrival_scale,
            "attempt_count": cell.reconciliation.attempt_count,
            "reconciled_count": cell.reconciliation.reconciled_count,
            "reconciled_fraction": cell.reconciliation.reconciled_fraction,
            "disagreement_fraction": cell.reconciliation.disagreement_fraction,
            "ledger_entries": len(cell.reconciliation.ledger),
            "truth_basis": cell.bundle.truth_basis.value,
            "tpot_reason": cell.bundle.tpot_reason,
            **labels,
        }
        for cell in outcome.cells
    ]
    ledger_rows = [
        {
            "arm_id": cell.arm_id,
            "arrival_scale": cell.arrival_scale,
            **_ledger_row("MODELED_REPLAY", entry),
        }
        for cell in outcome.cells
        for entry in cell.reconciliation.ledger
    ]
    ranking_rows = [
        {
            "metric": metric,
            "frozen_statistic": FROZEN_RANKING_STATISTIC,
            "left_label": "" if item is None else item.left_label,
            "right_label": "" if item is None else item.right_label,
            "tau_b": "" if item is None else item.tau_b,
            "pairwise_agreement": "" if item is None else item.pairwise_agreement,
            "concordant_pairs": "" if item is None else item.concordant_pairs,
            "discordant_pairs": "" if item is None else item.discordant_pairs,
            "available": item is not None,
            **labels,
        }
        for metric, item in rankings.items()
    ]
    # The policy is a nested mapping in the JSON record and has to be spread
    # across columns here, or the CSV cell would hold a repr of a dict and the
    # thresholds would be readable only by eye. They are the reason each verdict
    # came out the way it did, so they belong in the tabular artifact too.
    shadow_rows = [
        {
            "metric": metric,
            **{k: v for k, v in decision.to_dict().items() if k != "policy"},
            "reasons": "|".join(decision.reasons),
            **{f"policy_{k}": v for k, v in decision.policy.to_dict().items()},
        }
        for metric, decisions in shadow.items()
        for decision in decisions
    ]

    artifacts = {
        "replay.json": _json_bytes(payload),
        "results.csv": _csv_bytes(result_rows, list(result_rows[0])),
        "reconciliation.csv": _csv_bytes(
            reconciliation_rows, list(reconciliation_rows[0])
        ),
        # An empty modeled ledger is the expected outcome, so the field names are
        # declared rather than read off a first row that may not exist.
        "ledger.csv": _csv_bytes(
            ledger_rows, ["arm_id", "arrival_scale", *LEDGER_FIELDS]
        ),
        "fault_injection.csv": _csv_bytes(fault_rows, list(LEDGER_FIELDS)),
        "ranking.csv": _csv_bytes(ranking_rows, list(ranking_rows[0])),
        "shadow_decisions.csv": _csv_bytes(shadow_rows, list(shadow_rows[0])),
    }
    artifacts[MANIFEST_NAME] = _manifest_bytes(artifacts)

    for name, blob in sorted(artifacts.items()):
        _assert_no_stronger_claim(name, blob)
    _write_artifacts(output_dir, artifacts)

    for name in sorted(artifacts):
        print(f"wrote {output_dir / name} ({len(artifacts[name])} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
