#!/usr/bin/env python3
"""Calibrate against a real serving engine, or say precisely why it could not.

This is the hardware counterpart of ``run_m9_synthetic.py``. That script drives
:class:`MockEngine` and is therefore always able to finish; this one talks to an
engine over the versioned JSON contract in
:mod:`prefill_cache_sim.calibration.http_endpoint` and is *expected* to fail in
an environment without an accelerator.

Failing is the point. Run with no ``--endpoint-url`` and the script still
produces an artifact: a :class:`HardwareGateReport` whose ``blockers`` name
``BLOCKED_NO_ENGINE_ACCESS`` and whose labels stay ``SYNTHETIC_UNCALIBRATED`` /
``NORMALIZED_WORK`` / ``HARNESS_ONLY``. A reviewer asking "was M9 calibrated on
hardware?" gets a machine-readable no rather than an absent directory that could
mean anything.

Two properties keep that honest:

*Directory names carry the verdict.* An accepted run writes to
``results/m9-hardware``; a rejected one writes to ``results/m9-hardware-blocked``
and never touches the accepted path. There is no state in which a blocked run
leaves something a later reader could mistake for calibration.

*Labels are checked as bytes.* :func:`_assert_no_stronger_claim` scans every
artifact for ``HW_CALIBRATED``, ``MILLISECONDS`` and ``HW_VALIDATED`` *before*
any file reaches the output directory, and only permits them when the gate
accepted. A bug that mislabels a rejected run cannot publish.

Exit codes are distinct on purpose: ``0`` accepted, ``2`` rejected with a report
written, ``1`` the script itself failed. A CI job that treats "ran successfully"
as "calibrated" would be wrong, so rejection is not exit ``0``.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import math
import os
import shutil
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from prefill_cache_sim.calibration import (
    CALIBRATION_SCHEMA_VERSION,
    DEFAULT_HARDWARE_GATE,
    DISTRIBUTION_ASSUMPTION,
    ENDPOINT_CONTRACT_VERSION,
    MINIMUM_OBSERVATIONS,
    CalibrationParams,
    CalibrationStatus,
    EvidenceTier,
    HardwareContext,
    HardwareEvidence,
    HardwareGate,
    HttpJsonEngineEndpoint,
    HttpJsonTransport,
    LinearFit,
    SweepKind,
    SweepObservation,
    SweepSpec,
    TimeUnit,
    TrustPolicy,
    endpoint_is_synthetic,
    fit_sweep,
    residual_ratio,
    run_sweep,
    source_manifest,
)
from prefill_cache_sim.config import git_provenance
from prefill_cache_sim.trace import load_trace, to_simulation_requests

#: Recorded in the provenance block so the manifest names the generator that
#: actually ran rather than the synthetic one.
GENERATOR_PATH = "scripts/run_m9_hardware.py"

BATCH_POINTS = (1, 2, 4, 8, 16)
GRID_QUANTILES = (0.10, 0.25, 0.50, 0.75, 0.90, 0.99)
REPEATS = 3
BLOCK_SIZE_TOKENS = 512

ACCEPTED_DIR = "results/m9-hardware"
BLOCKED_DIR = "results/m9-hardware-blocked"

MANIFEST_NAME = "MANIFEST.json"
MANIFEST_SCHEMA_VERSION = "m9-hardware-manifest-v1"
GATE_NAME = "GATE.json"

#: Labels a rejected run has not earned. Checked against artifact bytes.
HARDWARE_LABELS = (
    CalibrationStatus.HW_CALIBRATED.value,
    TimeUnit.MILLISECONDS.value,
    EvidenceTier.HW_VALIDATED.value,
)


def _nearest_rank(ordered: list[int], quantile: float) -> int:
    index = max(1, math.ceil(quantile * len(ordered))) - 1
    return ordered[index]


def _token_points(values: list[int]) -> tuple[int, ...]:
    """Anchor the sweep axis on real trace quantiles, deduplicated and sorted.

    Deliberately the same construction as the synthetic runner. Calibrating on
    a grid the production trace does not visit would produce coefficients that
    are accurate about nothing anyone runs.
    """
    ordered = sorted(values)
    points = sorted({_nearest_rank(ordered, q) for q in GRID_QUANTILES})
    return tuple(point for point in points if point > 0)


def _json_bytes(payload: object) -> bytes:
    # allow_nan=False: a NaN latency that reached a fit must fail loudly here
    # rather than ship as an unparseable literal.
    return (
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n"
    ).encode("utf-8")


def _csv_bytes(rows: Sequence[Mapping[str, object]]) -> bytes:
    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(buffer, fieldnames=list(rows[0]))
    writer.writeheader()
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


def _manifest_bytes(artifacts: Mapping[str, bytes]) -> bytes:
    return _json_bytes(
        {
            "schema_version": MANIFEST_SCHEMA_VERSION,
            "algorithm": "sha256",
            "note": (
                "Digests of the artifacts generated by this run. This file is "
                "replaced last, so a reader that observes a digest mismatch is "
                "looking at a partially replaced set, not at one run's output."
            ),
            "files": {
                name: hashlib.sha256(payload).hexdigest()
                for name, payload in sorted(artifacts.items())
            },
        }
    )


def _assert_no_stronger_claim(name: str, payload: bytes, *, accepted: bool) -> None:
    """Refuse to publish a hardware label the gate did not grant.

    Unlike the synthetic runners, this script *can* legitimately emit
    ``HW_CALIBRATED``, so the check is conditional rather than absolute. The
    condition is the gate's verdict, which was derived from the evidence rather
    than asserted by this function's caller.
    """
    if accepted:
        return
    text = payload.decode("utf-8")
    for label in HARDWARE_LABELS:
        if label in text:
            raise RuntimeError(
                f"{name} claims {label} but the hardware gate rejected this run"
            )


def _write_artifacts(output_dir: Path, artifacts: Mapping[str, bytes]) -> None:
    """Stage every artifact, then move each into place with :func:`os.replace`.

    Per-file replacement rather than swapping the directory, so hand-written
    files that live alongside the generated ones survive. ``MANIFEST.json`` goes
    last and covers the rest, so a reader who catches the window between renames
    can detect the mix instead of trusting it.
    """
    if MANIFEST_NAME not in artifacts:
        raise RuntimeError(f"artifact set must include {MANIFEST_NAME}")
    ordered = [name for name in sorted(artifacts) if name != MANIFEST_NAME]
    ordered.append(MANIFEST_NAME)

    output_dir.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(dir=output_dir.parent, prefix=".m9hw-staging-"))
    try:
        for name in ordered:
            (staging / name).write_bytes(artifacts[name])
        for name in ordered:
            os.replace(staging / name, output_dir / name)
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def _fit_row(kind: str, fit: LinearFit) -> dict[str, Any]:
    return {
        "case_id": f"M9HW-{kind}",
        "sweep_kind": fit.kind.value,
        "intercept": fit.intercept,
        "token_coefficient": fit.token_coefficient,
        "batch_coefficient": fit.batch_coefficient,
        "observation_count": fit.observation_count,
        "residual_distribution_assumption": fit.residuals.distribution_assumption,
        "residual_p50": fit.residuals.p50,
        "residual_p90": fit.residuals.p90,
        "residual_p95": fit.residuals.p95,
        "residual_p99": fit.residuals.p99,
        "residual_max_abs": fit.residuals.maximum_absolute,
        "residual_mean_abs": fit.residuals.mean_absolute,
    }


def _measure(
    endpoint: HttpJsonEngineEndpoint, token_points: tuple[int, ...], repeats: int
) -> tuple[
    tuple[SweepObservation, ...],
    tuple[SweepObservation, ...],
    LinearFit | None,
    LinearFit | None,
]:
    """Sweep both kinds and fit them, returning ``None`` where a fit is refused.

    A fit that cannot be computed is returned as ``None`` rather than raised,
    because "too few points to fit" is a gate decision
    (``BLOCKED_FIT_UNAVAILABLE``) that belongs in the report next to the other
    blockers, not a traceback that produces no report at all.
    """
    prefill_spec = SweepSpec(
        SweepKind.PREFILL,
        token_points=token_points,
        batch_points=BATCH_POINTS,
        repeats=repeats,
    )
    decode_spec = SweepSpec(
        SweepKind.DECODE,
        token_points=token_points,
        batch_points=BATCH_POINTS,
        repeats=repeats,
    )
    prefill_observations = run_sweep(endpoint, prefill_spec)
    decode_observations = run_sweep(endpoint, decode_spec)

    def _fit(observations: tuple[SweepObservation, ...]) -> LinearFit | None:
        if len(observations) < MINIMUM_OBSERVATIONS:
            return None
        try:
            return fit_sweep(observations)
        except ValueError:
            # Degenerate grid: every point shares a token count or a batch size,
            # so the design matrix is singular. Reported as an unavailable fit.
            return None

    return (
        prefill_observations,
        decode_observations,
        _fit(prefill_observations),
        _fit(decode_observations),
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Calibrate M9 against a real engine. With no --endpoint-url this "
            "writes a BLOCKED_NO_ENGINE_ACCESS report and exits 2."
        )
    )
    parser.add_argument(
        "--endpoint-url",
        default=None,
        help=(
            "Base URL of a server speaking "
            f"{ENDPOINT_CONTRACT_VERSION}. http/https only; a file:// URL is "
            "refused because it would turn a hand-written JSON document into "
            "something that looks like an engine."
        ),
    )
    parser.add_argument(
        "--endpoint-id",
        default="engine-under-test",
        help="Identifier recorded in the artifact for the endpoint that was swept.",
    )
    parser.add_argument(
        "--timeout-s", type=float, default=30.0, help="Per-request deadline in seconds."
    )
    parser.add_argument(
        "--repeats",
        type=int,
        default=REPEATS,
        help="Repeats per grid point. More repeats shrink the residual ratio.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Perform the contract handshake and report what is on the other end "
            "without timing anything. Always rejected (BLOCKED_DRY_RUN_ONLY): a "
            "handshake is not a calibration."
        ),
    )
    parser.add_argument(
        "--trust-allowlist",
        default="",
        help=(
            "Comma-separated hostnames trusted to issue HW_CALIBRATED over "
            "HTTPS. An endpoint not on this list, or one speaking plain HTTP, "
            "publishes as REMOTE_REPORTED and cannot earn HW_CALIBRATED."
        ),
    )
    parser.add_argument(
        "--trace",
        default="mooncake_trace.jsonl",
        help="Trace whose token quantiles anchor the sweep grid.",
    )
    parser.add_argument(
        "--output-root",
        default=None,
        help=(
            "Directory under which the verdict directory is written. Defaults "
            "to the repository root. A test exercising the accepted path points "
            "this at a temporary directory so that a fixture can never leave a "
            "results/m9-hardware behind that a reader would take for a real "
            "calibration."
        ),
    )
    parser.add_argument(
        "--minimum-observations",
        type=int,
        default=DEFAULT_HARDWARE_GATE.minimum_observations,
        help="Gate policy: fewest observations that can support a fit.",
    )
    parser.add_argument(
        "--maximum-residual-ratio",
        type=float,
        default=DEFAULT_HARDWARE_GATE.maximum_residual_ratio,
        help="Gate policy: largest mean |residual| / mean |value| accepted.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    root = Path(__file__).resolve().parents[1]
    provenance = git_provenance(root)
    trust_policy = TrustPolicy(
        trusted_hosts=frozenset(
            host.strip() for host in args.trust_allowlist.split(",") if host.strip()
        )
    )
    production = (
        args.minimum_observations == DEFAULT_HARDWARE_GATE.minimum_observations
        and args.maximum_residual_ratio == DEFAULT_HARDWARE_GATE.maximum_residual_ratio
    )
    gate = HardwareGate(
        minimum_observations=args.minimum_observations,
        maximum_residual_ratio=args.maximum_residual_ratio,
        production=production,
    )

    endpoint: HttpJsonEngineEndpoint | None = None
    context = HardwareContext.unknown()
    prefill_fit: LinearFit | None = None
    tpot_fit: LinearFit | None = None
    prefill_observations: tuple[SweepObservation, ...] = ()
    decode_observations: tuple[SweepObservation, ...] = ()
    token_points: tuple[int, ...] = ()
    handshake_error: str | None = None

    if args.endpoint_url:
        endpoint = HttpJsonEngineEndpoint(
            endpoint_id=args.endpoint_id,
            transport=HttpJsonTransport(
                base_url=args.endpoint_url, timeout_s=args.timeout_s
            ),
        )
        # The handshake is allowed to fail without killing the run: an
        # unreachable or non-conforming engine is exactly the condition the
        # blocker vocabulary exists to name.
        try:
            context = endpoint.describe()
        except Exception as error:  # noqa: BLE001 - recorded, then reported
            handshake_error = f"{type(error).__name__}: {error}"
            endpoint = None

    if endpoint is not None and not args.dry_run:
        loaded = load_trace(root / args.trace, block_size_tokens=BLOCK_SIZE_TOKENS)
        requests = to_simulation_requests(loaded)
        token_points = _token_points([item.input_tokens for item in requests])
        (
            prefill_observations,
            decode_observations,
            prefill_fit,
            tpot_fit,
        ) = _measure(endpoint, token_points, args.repeats)

    observations = prefill_observations + decode_observations
    ratio: float | None = None
    if prefill_fit is not None and tpot_fit is not None:
        # The worse of the two: a run whose prefill fits tightly and whose
        # decode does not has not calibrated the engine, and averaging would
        # let the good half hide the bad one.
        ratio = max(
            residual_ratio(prefill_fit, prefill_observations),
            residual_ratio(tpot_fit, decode_observations),
        )

    evidence = HardwareEvidence(
        engine_reachable=endpoint is not None,
        endpoint_is_synthetic=(
            True if endpoint is None else endpoint_is_synthetic(endpoint)
        ),
        production_trust=(
            endpoint is not None
            and not endpoint_is_synthetic(endpoint)
            and trust_policy.is_production_trusted(args.endpoint_url or "")
        ),
        observed_contract_version=context.endpoint_contract_version,
        observation_count=len(observations),
        fit_residual_ratio=ratio,
        dry_run=bool(args.dry_run),
    )
    report = gate.evaluate(context, evidence)
    accepted = report.accepted

    artifacts: dict[str, bytes] = {
        GATE_NAME: _json_bytes(
            {
                "report": report.to_dict(),
                "handshake_error": handshake_error,
                "endpoint_url_provided": bool(args.endpoint_url),
                "provenance": {
                    "git_sha": provenance.sha,
                    "git_dirty": provenance.dirty,
                    "source_fingerprints": source_manifest(root, GENERATOR_PATH),
                    "schema_version": CALIBRATION_SCHEMA_VERSION,
                },
            }
        )
    }

    if accepted:
        if prefill_fit is None or tpot_fit is None:
            # Unreachable through the gate, which blocks on BLOCKED_FIT_UNAVAILABLE
            # before it can accept. Kept as a raise rather than an assert because
            # -O would strip the assert and let a None reach CalibrationParams.
            raise RuntimeError("gate accepted a run with no fit")
        params = CalibrationParams(
            endpoint_id=args.endpoint_id,
            machine=context.machine,
            calibration_status=report.calibration_status,
            time_unit=report.time_unit,
            evidence_tier=report.evidence_tier,
            prefill=prefill_fit,
            tpot=tpot_fit,
            code_sha=provenance.sha,
            code_dirty=provenance.dirty,
        )
        if CalibrationParams.from_dict(params.to_dict()) != params:
            raise RuntimeError("calibration params failed to round-trip")
        artifacts["params.json"] = _json_bytes(
            {
                "params": params.to_dict(),
                "hardware_context": context.to_dict(),
                "grid": {
                    "token_points": list(token_points),
                    "batch_points": list(BATCH_POINTS),
                    "repeats": args.repeats,
                },
                "provenance": {
                    "git_sha": provenance.sha,
                    "git_dirty": provenance.dirty,
                    "source_fingerprints": source_manifest(root, GENERATOR_PATH),
                    "distribution_assumption": DISTRIBUTION_ASSUMPTION,
                    "schema_version": CALIBRATION_SCHEMA_VERSION,
                },
            }
        )
        artifacts["results.csv"] = _csv_bytes(
            [_fit_row("PREFILL", prefill_fit), _fit_row("TPOT", tpot_fit)]
        )
        artifacts["observations.csv"] = _csv_bytes(
            [
                {**item.to_dict(), "endpoint_id": args.endpoint_id}
                for item in observations
            ]
        )

    artifacts[MANIFEST_NAME] = _manifest_bytes(artifacts)
    for name, blob in sorted(artifacts.items()):
        _assert_no_stronger_claim(name, blob, accepted=accepted)

    output_root = Path(args.output_root).resolve() if args.output_root else root
    output_dir = output_root / (ACCEPTED_DIR if accepted else BLOCKED_DIR)
    _write_artifacts(output_dir, artifacts)

    for name in sorted(artifacts):
        print(f"wrote {output_dir / name} ({len(artifacts[name])} bytes)")
    if accepted:
        print("M9-HW accepted: HW_CALIBRATED")
        return 0
    print("M9-HW blocked: " + ", ".join(item.value for item in report.blockers))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
